"""Compare directional travel times between adjacent platforms.

The script uses the cleaned GTFS file generated by the data checking notebooks:

- stop_times_cleaned.txt, filtering rows where ``trip_id`` starts with ``1.``

For each directed adjacent pair of stops ``(a, b)``, the script computes the
average travel time from the departure time at ``a`` to the arrival time at
``b``. It then compares that average with the reverse direction ``(b, a)`` and
prints the pairs with the largest absolute differences.
"""

from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path
from statistics import mean
from typing import DefaultDict, Dict, List, Sequence, Set, Tuple


_PROJECT_ROOT = str(Path(__file__).resolve().parents[1])
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

from data_validation.gtfs_utils import (  # noqa: E402
    STOP_TIMES_CLEANED_FILE,
    check_missing_files,
    read_dict_rows,
)


SECONDS_PER_DAY = 24 * 60 * 60
TOP_PAIRS_TO_PRINT = 10


def parse_gtfs_time(value: str) -> int:
    """Convert a GTFS HH:MM:SS time string to seconds.

    args:
            value: Time text in HH:MM:SS format.

    returns:
            Total seconds represented by the input time.
    """

    hours_text, minutes_text, seconds_text = value.strip().split(":")
    return int(hours_text) * 3600 + int(minutes_text) * 60 + int(seconds_text)


def format_seconds(value: float) -> str:
    """Format a duration in seconds as HH:MM:SS with optional sign.

    args:
            value: Duration in seconds.

    returns:
            Formatted duration string.
    """

    sign = "-" if value < 0 else ""
    rounded = int(round(abs(value)))
    hours, remainder = divmod(rounded, 3600)
    minutes, seconds = divmod(remainder, 60)
    return f"{sign}{hours:02d}:{minutes:02d}:{seconds:02d}"


def build_directed_pair_samples(
    stop_times_file: str,
) -> Dict[Tuple[str, str], List[int]]:
    """Collect travel-time samples for directed adjacent stop pairs in trips 1.*.

    args:
            stop_times_file: Path to stop_times_cleaned.txt.

    returns:
            Mapping from directed stop pair (a, b) to observed travel times in seconds.
    """

    pair_samples: DefaultDict[Tuple[str, str], List[int]] = defaultdict(list)
    rows: List[Tuple[str, int, str, str, str]] = []

    for row in read_dict_rows(stop_times_file):
        trip_id = row.get("trip_id", "").strip()
        if not trip_id.startswith("1."):
            continue

        sequence_text = row.get("stop_sequence", "").strip()
        stop_id = row.get("stop_id", "").strip()
        arrival_time = row.get("arrival_time", "").strip()
        departure_time = row.get("departure_time", "").strip()

        if not sequence_text or not stop_id:
            continue

        try:
            stop_sequence = int(sequence_text)
        except ValueError:
            continue

        rows.append((trip_id, stop_sequence, stop_id, arrival_time, departure_time))

    rows.sort(key=lambda item: (item[0], item[1]))

    for current_row, next_row in zip(rows, rows[1:]):
        current_trip_id, current_sequence, current_stop_id, _, current_departure = (
            current_row
        )
        next_trip_id, next_sequence, next_stop_id, next_arrival, _ = next_row

        if current_trip_id != next_trip_id:
            continue
        if next_sequence != current_sequence + 1:
            continue
        if not current_departure or not next_arrival:
            continue

        travel_time = parse_gtfs_time(next_arrival) - parse_gtfs_time(current_departure)
        # Handle day rollover (e.g. 23:59:50 -> 00:00:10 gives -86380, then +86400 = 20).
        while travel_time < 0:
            travel_time += SECONDS_PER_DAY

        pair_samples[(current_stop_id, next_stop_id)].append(travel_time)

    return dict(pair_samples)


def summarize_directional_gaps(
    pair_samples: Dict[Tuple[str, str], List[int]]
) -> List[Tuple[float, Tuple[str, str], float, float]]:
    """Return reciprocal stop pairs ranked by directional-average gap.

    args:
            pair_samples: Mapping of directed stop pairs to travel-time samples.

    returns:
            Sorted list of tuples: gap, unordered pair, w_a_b, w_b_a.
    """

    pair_averages = {
        pair: mean(samples) for pair, samples in pair_samples.items() if samples
    }

    seen_pairs: Set[Tuple[str, str]] = set()
    ranked_pairs: List[Tuple[float, Tuple[str, str], float, float]] = []

    for (stop_a, stop_b), average_ab in pair_averages.items():
        normalized_pair = (stop_a, stop_b) if stop_a <= stop_b else (stop_b, stop_a)
        if normalized_pair in seen_pairs:
            continue

        average_ba = pair_averages.get((stop_b, stop_a))
        if average_ba is None:
            continue

        seen_pairs.add(normalized_pair)
        ranked_pairs.append(
            (
                abs(average_ab - average_ba),
                normalized_pair,
                average_ab,
                average_ba,
            )
        )

    ranked_pairs.sort(key=lambda item: (-item[0], item[1][0], item[1][1]))
    return ranked_pairs


def print_summary(
    ranked_pairs: Sequence[Tuple[float, Tuple[str, str], float, float]]
) -> None:
    """Print a summary for the ranked directional gaps.

    args:
            ranked_pairs: Ranked reciprocal pairs with directional averages and gaps.
    """

    print(
        "Number of stop pairs with both directions defined:",
        len(ranked_pairs),
    )

    if not ranked_pairs:
        print("No reciprocal stop pairs were found.")
        return

    print("Top pairs by absolute directional difference:")
    for index, (difference, pair, average_ab, average_ba) in enumerate(
        ranked_pairs[:TOP_PAIRS_TO_PRINT], start=1
    ):
        print(
            f"{index}. ({pair[0]}, {pair[1]}) - "
            f"|w_a_b - w_b_a| = {difference:.2f}s ({format_seconds(difference)}), "
            f"w_a_b = {average_ab:.2f}s ({format_seconds(average_ab)}), "
            f"w_b_a = {average_ba:.2f}s ({format_seconds(average_ba)})"
        )


def main() -> None:
    """Run the between-platforms analysis."""

    check_missing_files([STOP_TIMES_CLEANED_FILE])

    pair_samples = build_directed_pair_samples(STOP_TIMES_CLEANED_FILE)
    ranked_pairs = summarize_directional_gaps(pair_samples)
    print_summary(ranked_pairs)


if __name__ == "__main__":
    main()
